### PR TITLE
Updates for August 1, 2024

### PR DESCRIPTION
**Pull request by jerinjoy**
Bug fixes and features including virtualization.

### CODE REVIEW

**Comment by jerinjoy** [comment]
cc @aditmohan96 I can't seem to add you as a reviewer.

**Comment by aditmohan96** [comment]
https://github.com/rivosinc/JumpStart/pull/21/commits/096a652a796fd7811e14be2b7f93ff19bcf6deda

maybe change the commit message here ?

**Comment by jerinjoy** [comment]
The failure is due to a recent Spike change. Filed:
https://github.com/riscv-software-src/riscv-isa-sim/issues/1755

**Comment by jerinjoy** [comment]
> [096a652](https://github.com/rivosinc/JumpStart/commit/096a652a796fd7811e14be2b7f93ff19bcf6deda)
> 
> maybe change the commit message here ?

Done.

**Pull request merged**
